output-format: text

strictness: high

autodetect: false

ignore-paths:
  - build
  - dist
  - docs

max-line-length: 120

pylint:
    max-line-length: 120

pep8:
  full: true
  options:
    max-line-length: 120

pyroma:
  run: true
