version: "3"
services:
    hydra:
        image: "hydra:dev"
        build:
            context: .
            dockerfile: Dockerfile
        hostname: hydra
        stdin_open: true
        tty: true
        working_dir: '/hydra-dev'
        volumes:
            - ".:/hydra-dev"
